#!/bin/bash

# -------------------------------------------------------------------------------------------
#                                 Setup all the Variables and Paths
# -------------------------------------------------------------------------------------------
echo "------------------------------------ VARIABLES ----------------------------------------"

# Establish the base repository reference directory
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPOSITORY_DIR="$( dirname $THIS_DIR )"
REPOSITORY_CONFIG_FILE="$REPOSITORY_DIR/repository-setup/repository-config.ini"

echo "THIS_DIR=$THIS_DIR"
echo "REPOSITORY_DIR=$REPOSITORY_DIR"
echo "REPOSITORY_CONFIG_FILE=$REPOSITORY_CONFIG_FILE"

if [ ! -f $REPOSITORY_CONFIG_FILE ]; then
    echo "ERROR: Repository config file not found."
    echo "    location=$REPOSITORY_CONFIG_FILE"
    exit 1
fi

# Setup our local directory
CACHE_DIR="$REPOSITORY_DIR/.cache"
if [ ! -d $CACHE_DIR ]; then
    mkdir $CACHE_DIR
fi

INITIALIZED_FILE="$CACHE_DIR/initialized"
REPOSITORY_CONFIG_INI_FILE="$RESPOSITORY_DIR/repository-setup/repository-config.ini"
VIRTUAL_ENV_DIR="$REPOSITORY_DIR/.venv"
VIRTUAL_ENV_BIN_DIR="$VIRTUAL_ENV_DIR/bin"

ENV_FILE="$REPOSITORY_DIR/.env"
if [ ! -f $ENV_FILE ]; then
    echo "ERROR: Development environment file not found. Did you run the 'repository-setup' script."
    echo "    location=$ENV_FILE"
    exit 1
fi

echo "ENV_FILE=$ENV_FILE"

CUSTOM_CLI_ALIAS=""
CUSTOM_CLI_ENTRY_SCRIPT=""
PROJECT_NAME=""
PYTHON_VERSION=""

source $ENV_FILE
source $(grep --color=never -E "^[\s]*[A-Za-z_]+[A-Za-z_0-9]*=" "$REPOSITORY_CONFIG_INI_FILE")

# The PYTHON_VERSION can be pinned in the development environment config
if [ -z "$PYTHON_VERSION" ]
then
    echo "ERROR: The 'PYTHON_VERSION' variable should be set in the development environment file."
    echo "    location=$ENV_FILE"
    exit 1
fi

echo "CUSTOM_CLI_ALIAS=$CUSTOM_CLI_ALIAS"
echo "CUSTOM_CLI_ENTRY_SCRIPT=$CUSTOM_CLI_ENTRY_SCRIPT"
echo "PROJECT_NAME=$PROJECT_NAME"
echo "PYTHON_VERSION=$PYTHON_VERSION"
echo "VIRTUAL_ENV_DIR=$VIRTUAL_ENV_DIR"
echo "VIRTUAL_ENV_BIN_DIR=$VIRTUAL_ENV_BIN_DIR"

echo "---------------------------------------------------------------------------------------"


# -------------------------------------------------------------------------------------------
#                                 Perform Reset if Required
# -------------------------------------------------------------------------------------------
if [ "$1" == "reset" ]; then
    rm -fr $VIRTUAL_ENV_DIR
    rm -f $INITIALIZED_FILE
fi

# -------------------------------------------------------------------------------------------
#                                 Virtual Environment Commanline Customization
# -------------------------------------------------------------------------------------------
function customize_activate_script() {
    
    echo "# ================ Development Environment Customizations ================"
    echo ""  >> $ACTIVATE_SCRIPT
    echo "if [ -f $ENV_FILE ]" >> $ACTIVATE_SCRIPT
    echo "then" >> $ACTIVATE_SCRIPT
    echo "    set -a" >> $ACTIVATE_SCRIPT
    echo "    source $ENV_FILE" >> $ACTIVATE_SCRIPT
    echo "    set +a" >> $ACTIVATE_SCRIPT
    echo "fi" >> $ACTIVATE_SCRIPT
    echo "" >> $ACTIVATE_SCRIPT

    # Check for custom commandline additions
    if [ ! -z "$CUSTOM_CLI_ALIAS" ] || [ ! -z "$CUSTOM_CLI_ENTRY_SCRIPT" ];
    then
        if [ ! -z "$CUSTOM_CLI_ALIAS" ] && [ ! -z "$CUSTOM_CLI_ENTRY_SCRIPT" ];
        then
            echo "# Create an alias for the $CUSTOM_CLI_ALIAS command" >> $ACTIVATE_SCRIPT
            echo "function $CUSTOM_CLI_ALIAS () {" >> $ACTIVATE_SCRIPT
            echo "    \"$VIRTUAL_ENV_BIN_DIR/python3\" \"$CUSTOM_CLI_ENTRY_SCRIPT\" \$@ " >> $ACTIVATE_SCRIPT
            echo "}"  >> $ACTIVATE_SCRIPT
            echo "export -f $CUSTOM_CLI_ALIAS"  >> $ACTIVATE_SCRIPT
            echo ""  >> $ACTIVATE_SCRIPT
        fi
    else
        echo "To add a custom commandline, you must set both 'CUSTOM_CLI_ALIAS' and 'CUSTOM_CLI_ENTRY_SCRIPT'"
        exit 1
    fi
    
}

# -------------------------------------------------------------------------------------------
#                                 Create the Virtual Environment
# -------------------------------------------------------------------------------------------
echo
echo
echo "---------------------------- VIRTUAL ENVIRONMENT CREATION -----------------------------"
if [ ! -f $INITIALIZED_FILE ]; then

    pushd $REPOSITORY_DIR

    if [ ! -f $VIRTUAL_ENV_DIR/bin/activate ]; then
        
        poetry env use $PYTHON_VERSION
    else
        echo "ERROR: Unable to create or find the python virtual environment"
        exit 1
    fi

    poetry update --no-cache

    popd

    customize_activate_script

    touch $INITIALIZED_FILE

else
    echo "Virtual environment already intialized..."

fi

echo "---------------------------------------------------------------------------------------"
