
INTEGRATION_CLASS_NETWORK_DLIPOWER = "network/dlipower"
INTEGRATION_CLASS_NETWORK_MDNS = "network/mdns"
INTEGRATION_CLASS_NETWORK_SSH = "network/ssh"
INTEGRATION_CLASS_NETWORK_TCPSERIAL = "network/tcpserial"
INTEGRATION_CLASS_NETWORK_UPNP = "network/upnp"

